spring:
    application:
        name: GatewayService
    cloud:
        gateway:
            routes:
                -   id: dorm-service1
                    uri: lb://dorm-service
                    predicates:
                        - Path=/api/*/dorm/**
                -   id: dorm-service2
                    uri: lb://dorm-service
                    predicates:
                        - Path=/api/*/building/**
                -   id: dorm-service3
                    uri: lb://dorm-service
                    predicates:
                        - Path=/api/*/admin/**
                -   id: room-service1
                    uri: lb://room-service
                    predicates:
                        - Path=/api/*/room/**
                -   id: room-service2
                    uri: lb://room-service
                    predicates:
                        - Path=/api/*/furniture/**
                -   id: room-service3
                    uri: lb://room-service
                    predicates:
                        - Path=/api/*/catalog/**
                -   id: rent-service1
                    uri: lb://rent-service
                    predicates:
                        - Path=/api/*/rent/**
                -   id: rent-service2
                    uri: lb://rent-service
                    predicates:
                        - Path=/api/*/tenant/**
                -   id: rent-service3
                    uri: lb://rent-service
                    predicates:
                        - Path=/api/*/invoice/**
                -   id: rent-service4
                    uri: lb://rent-service
                    predicates:
                        - Path=/api/*/receipt/**
            globalcors:
                corsConfigurations:
                    '[/**]':
                        allowedOrigins: "*"
                        allowedMethods:
                            - GET
                            - POST
                            - PUT
                            - DELETE
                        allowedHeaders:
                            - "Authorization"
                            - "Content-Type"
                            - "X-Requested-With"
                            - "accept"
                            - "Origin"
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        preferIpAddress: true
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.uuid}}
        leaseRenewalIntervalInSeconds: 5
        leaseExpirationDurationInSeconds: 10

server:
    port: 8080

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always