spring:
    application:
        name: GatewayService
    cloud:
        gateway:
            routes:
                -   id: dorm-service1
                    uri: lb://dorm-service
                    predicates:
                        - Path=/api/*/dorm/**
                -   id: dorm-service2
                    uri: lb://dorm-service
                    predicates:
                        - Path=/api/*/building/**
                -   id: dorm-service3
                    uri: lb://dorm-service
                    predicates:
                        - Path=/api/*/admin/**
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        preferIpAddress: true
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.uuid}}
        leaseRenewalIntervalInSeconds: 5
        leaseExpirationDurationInSeconds: 10

server:
    port: 8080

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always