openapi: 3.0.0
info:
  title: Dorm Management API
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/PhannakonPhungamngoen/DormProjectForSoftdev/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://ip:port/<serviceName>
  description: Localhost
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /receipts:
    get:
      summary: Get all receipts
      operationId: getAllReceipts
      responses:
        "200":
          description: List of receipts
          content:
            application/json:
              schema:
                type: object
                properties:
                  StatusCode:
                    type: string
                  Message:
                    type: string
                  Data:
                    type: array
                    items:
                      $ref: './components.yml#/components/schemas/Receipt'
        "401":
          $ref: './components.yml#/components/responses/UnauthorizedError'
        "403":
          $ref: './components.yml#/components/responses/ForbiddenError'
    post:
      summary: Add a new receipt
      operationId: addReceipt
      requestBody:
        content:
          application/json:
            schema:
              $ref: './components.yml#/components/schemas/Receipt'
        required: true
      responses:
        "201":
          description: Receipt added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  StatusCode:
                    type: string
                  Message:
                    type: string
                  Data:
                    $ref: './components.yml#/components/schemas/Receipt'
        "401":
          $ref: './components.yml#/components/responses/UnauthorizedError'
        "403":
          $ref: './components.yml#/components/responses/ForbiddenError'
  /receipts/{id}:
    get:
      summary: Get receipt by ID
      operationId: getReceiptById
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        description: ID of the receipt to retrieve
      responses:
        "200":
          description: Receipt data
          content:
            application/json:
              schema:
                type: object
                properties:
                  StatusCode:
                    type: string
                  Message:
                    type: string
                  Data:
                    $ref: './components.yml#/components/schemas/Receipt'
        "401":
          $ref: './components.yml#/components/responses/UnauthorizedError'
        "403":
          $ref: './components.yml#/components/responses/ForbiddenError'
        "404":
          $ref: './components.yml#/components/responses/NotFoundError'
    put:
      summary: Update receipt by ID
      operationId: updateReceipt
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        description: ID of the receipt to update
      requestBody:
        content:
          application/json:
            schema:
              $ref: './components.yml#/components/schemas/Receipt'
        required: true
      responses:
        "200":
          description: Receipt updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  StatusCode:
                    type: string
                  Message:
                    type: string
                  Data:
                    $ref: './components.yml#/components/schemas/Receipt'
        "401":
          $ref: './components.yml#/components/responses/UnauthorizedError'
        "403":
          $ref: './components.yml#/components/responses/ForbiddenError'
        "404":
          $ref: './components.yml#/components/responses/NotFoundError'
    delete:
      summary: Delete receipt by ID
      operationId: deleteReceipt
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        description: ID of the receipt to delete
      responses:
        "204":
          description: Receipt deleted successfully
        "401":
          $ref: './components.yml#/components/responses/UnauthorizedError'
        "403":
          $ref: './components.yml#/components/responses/ForbiddenError'
        "404":
          $ref: './components.yml#/components/responses/NotFoundError'
